name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    permissions:
      contents: read

  changesets:
    name: Create version pull request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Create Version Pull Request
        uses: changesets/action@v1
        with:
          commit: "chore: version package"
          title: "chore: version package"
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Publish release
    needs: [verify]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # To push commits and tags
      pull-requests: write # To create and update PRs
      id-token: write # For NPM provenance
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Setup Node.js for NPM
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"

      - name: Publish to NPM
        uses: changesets/action@v1
        with:
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
          publish: pnpm changeset:publish
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
